src/main/java/ar/edu/unnoba/poo2018/ods/model/Actividad.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.edu.unnoba.poo2018.ods.model;

import java.util.Date;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *
 * @author Asus
 */
@Entity
@Inheritance(strategy=InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name="tipo")
@Table(name="actividad")
@NamedQueries({
    @NamedQuery(name = "Actividad.busqueda", query = "SELECT a FROM Actividad a INNER JOIN a.usuarios u WHERE a.fecha_inicio>= :desde AND a.fecha_fin<= :hasta AND u.mail =:mail"),
    @NamedQuery(name = "Actividad.actividadesUsuario", query = "SELECT a FROM Actividad a INNER JOIN a.usuarios u WHERE u.mail =:mail"),
    @NamedQuery(name = "Actividad.findAll", query = "SELECT u FROM Actividad u")
})
public abstract class Actividad extends AbstractEntity{
    @ManyToMany(mappedBy="actividades", cascade = CascadeType.ALL)
    private List<Usuario> usuarios;
    @Column(name="tipo")
    private String tipo;
    @Column(name="nombre")
    private String nombre;
    @Column(name="fecha_inicio")
    @Temporal(TemporalType.DATE)
    private Date fecha_inicio;
    @Column(name="fecha_fin")
    @Temporal(TemporalType.DATE)
    private Date fecha_fin;
    @Column(name="resolucion")
    private String resolucion;
    @Column(name="expediente")
    private String expediente;
    @ManyToOne
    @JoinColumns(
        @JoinColumn(name="convocatoria_id",referencedColumnName = "id")
    )
    private Convocatoria convocatoria;
    @ManyToOne
    @JoinColumns(
        @JoinColumn(name="linea_estrategia_id",referencedColumnName = "id")
    )
    private LineaEstrategia lineaEstrategia;
    @ManyToOne
    @JoinColumns(
        @JoinColumn(name="ambito_id",referencedColumnName = "id")
    )
    private AmbitoDeEjecucion ambitoDeEjecucion;

    public Actividad() {
    }
    
    public abstract int getPeso();    
    public abstract double calcularPorcentaje();

    
    public List<Usuario> getUsuarios() {
        return usuarios;
    }

    public void setUsuarios(List<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    
    
        
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFecha_inicio() {
        return fecha_inicio;
    }

    public void setFecha_inicio(Date fecha_inicio) {
        this.fecha_inicio = fecha_inicio;
    }

    public Date getFecha_fin() {
        return fecha_fin;
    }

    public void setFecha_fin(Date fecha_fin) {
        this.fecha_fin = fecha_fin;
    }

    public String getResolucion() {
        return resolucion;
    }

    public void setResolucion(String resolucion) {
        this.resolucion = resolucion;
    }

    public String getExpediente() {
        return expediente;
    }

    public void setExpediente(String expediente) {
        this.expediente = expediente;
    }

    public Convocatoria getConvocatoria() {
        return convocatoria;
    }

    public void setConvocatoria(Convocatoria convocatoria) {
        this.convocatoria = convocatoria;
    }

    public LineaEstrategia getLineaEstrategia() {
        return lineaEstrategia;
    }

    public void setLineaEstrategia(LineaEstrategia lineaEstrategia) {
        this.lineaEstrategia = lineaEstrategia;
    }

    public AmbitoDeEjecucion getAmbitoDeEjecucion() {
        return ambitoDeEjecucion;
    }

    public void setAmbitoDeEjecucion(AmbitoDeEjecucion ambitoDeEjecucion) {
        this.ambitoDeEjecucion = ambitoDeEjecucion;
    }

    public String getTipo() {
        return tipo;
    }
    
    
    
    
}

src/main/webapp/actividad/simple/edit.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="../../template.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">

    <f:metadata>
        <f:viewParam name="id" 
                     value="#{actividadSimpleBacking.actividadSimple}" 
                     converter="actividadSimpleConverter"/>
    </f:metadata>
    
    <ui:define name="content">


        <h:form id="simple_edit">
            <p:messages autoUpdate="true"/>
            
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p:panel class="panel-auto" style="margin-top:20px" header="#{msg.actualizarActividadSimple}" >
                            <h:panelGrid columns="6" cellpadding="5" >
                                <p:outputLabel for="nombre" value="#{msg.nombre}:" />
                                <p:inputText id="nombre" value="#{actividadSimpleBacking.actividadSimple.nombre}" /> 
                                <p:outputLabel for="fecha_inicio" value="#{msg.fecha_inicio}:" />
                                <p:calendar id="fecha_inicio" value="#{actividadSimpleBacking.actividadSimple.fecha_inicio}" />
                                <p:outputLabel for="fecha_fin" value="#{msg.fecha_fin}:" />
                                <p:calendar id="fecha_fin" value="#{actividadSimpleBacking.actividadSimple.fecha_fin}"  />

                                <p:outputLabel for="resolucion" value="#{msg.resolucion}:" />
                                <p:inputText id="resolucion" value="#{actividadSimpleBacking.actividadSimple.resolucion}"/> 

                                <p:outputLabel for="expediente" value="#{msg.expediente}:" />
                                <p:inputText id="expediente" value="#{actividadSimpleBacking.actividadSimple.expediente}" />

                            </h:panelGrid>

                            <h:panelGrid columns="6" cellpadding="5" >
                                <p:outputLabel for="convocatoria" value="#{msg.convocatoria}:" />
                                <p:selectOneMenu id="convocatoria" value="#{actividadSimpleBacking.actividadSimple.convocatoria}" converter="convocatoriaConverter" filter="true" >
                                    <f:selectItem itemLabel="#{msg.elegir}" itemValue="#{null}" noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{actividadSimpleBacking.listaDeConvocatorias()}" var="convocatorias" itemLabel="#{convocatorias.nombre}" itemValue="#{convocatorias}" />
                                </p:selectOneMenu>

                                <p:outputLabel for="lineaEstrategia" value="#{msg.LineaEstrategia}:" />
                                <p:selectOneMenu id="lineaEstrategia" value="#{actividadSimpleBacking.actividadSimple.lineaEstrategia}" converter="lineaDeEstrategiaConverter" filter="true">
                                    <f:selectItem itemLabel="#{msg.elegir}" itemValue="#{null}" noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{actividadSimpleBacking.listaDeEstrategias()}" var="estrategias" itemLabel="#{estrategias.nombre}" itemValue="#{estrategias}" />
                                </p:selectOneMenu>

                                <p:outputLabel for="ambito" value="#{msg.ambitoEjecucion}:" />
                                <p:selectOneMenu id="ambito" value="#{actividadSimpleBacking.actividadSimple.ambitoDeEjecucion}" converter="ambitoDeEjecucionConverter" filter="true">
                                    <f:selectItem itemLabel="#{msg.elegir}" itemValue="#{null}" noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{actividadSimpleBacking.listaDeAmbitos()}" var="ambitos" itemLabel="#{ambitos.nombre}" itemValue="#{ambitos}" />
                                </p:selectOneMenu>
                            </h:panelGrid>
                             <p:separator />
                             <h:panelGrid columns="5"  >
                                <p:outputLabel value="#{msg.objetivos}"></p:outputLabel>
                                <p:selectOneMenu value="#{actividadSimpleBacking.impactoObjetivo.ods}" converter="odsConverter">
                                    <f:selectItem itemLabel="#{msg.elegir}" itemValue="#{null}" noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{actividadSimpleBacking.objetivos}" 
                                                   var="objetivo" itemLabel="#{objetivo.nombre}"/>
                                </p:selectOneMenu>
                                <p:outputLabel value="Peso"></p:outputLabel>
                                <p:inputText value="#{actividadSimpleBacking.impactoObjetivo.peso}"/>
                                <p:commandButton value="Agregar impacto" 
                                                 actionListener="#{actividadSimpleBacking.insertarImpacto()}" 
                                                 update="actividad_impactos"/>
                            </h:panelGrid>
                             <p:separator />
                            <h:panelGrid id="tabla" columns="1" cellpadding="5"  >
                                <p:dataTable id="actividad_impactos" value="#{actividadSimpleBacking.actividadSimple.impactoObjetivo}" var="impacto">
                                    <p:column headerText="Objetivo">#{impacto.ods.nombre}</p:column>
                                    <p:column headerText="Peso">#{impacto.peso}</p:column>
                                    <p:column>
                                        <p:commandLink actionListener="#{actividadSimpleBacking.borrarImpacto(impacto)}" 
                                                       value="#{msg.eliminar}" update="actividad_impactos"/>
                                    </p:column>
                                </p:dataTable>
                                <p:commandButton value="#{msg.actualizar}" 
                                                 action="#{actividadSimpleBacking.update()}" 
                                                 update="simple_edit"/>

                                <p:button outcome="/actividad/simple/index" 
                                          value="#{msg.volver}"/>
                            </h:panelGrid>


                        </p:panel>
                    </div>
                </div>
            </div>
        </h:form>
    </ui:define>    
</ui:composition>

src/main/webapp/actividad/simple/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="../../template.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ui:define name="content">
        <h:form id="simple_index">
 
            <p:dataTable var="actividad" 
                         value="#{actividadSimpleBacking.findAll()}"  emptyMessage="#{msg.nohayactividades}">

                <p:column headerText="#{msg.actividadessimples}" width="300">
                    <h:outputText value="#{actividad.nombre}" />
                </p:column>
                <p:column headerText="#{msg.fecha_inicio}">
                    <h:outputText value="#{actividad.fecha_inicio}" >
                        <f:convertDateTime pattern="dd/MM" type="date" />
                    </h:outputText>
                </p:column>
                <p:column headerText="#{msg.fecha_fin}">
                    <h:outputText value="#{actividad.fecha_fin}" >
                        <f:convertDateTime pattern="dd/MM" type="date" />
                    </h:outputText>
                </p:column>
                <p:column headerText="#{msg.peso}">
                    <h:outputText value="#{actividad.peso}" />
                </p:column>
                <p:column headerText="#{msg.acciones}" width="200">
                    <p:button value="#{msg.editar}" 
                              outcome="edit.xhtml">
                        <f:param name="id"
                                 value="#{actividad.id}"/>
                    </p:button>
                    

                    <p:commandButton value="#{msg.eliminar}" 
                                     action="#{actividadSimpleBacking.delete(actividad)}">
                    </p:commandButton>

                </p:column>

            </p:dataTable>
        </h:form>
    </ui:define>    
</ui:composition>

src/main/webapp/actividad/simple/new.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                template="../../template.xhtml/"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html">
    <ui:define name="content">


        <h:form id="simple_new" >
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p:panel class="panel-auto" style="margin-top:0px; margin-bottom: 0px" header="#{msg.nuevaActSimple}" >
                            <h:panelGrid columns="6" cellpadding="1" style="margin-top:0px; margin-bottom: 0px" >
                                <p:outputLabel for="nombre" value="#{msg.nombre}:" />
                                <p:inputText id="nombre" value="#{actividadSimpleBacking.actividadSimple.nombre}" 
                                             required="true" 
                                             requiredMessage="#{msg.camporequerido}"/> 
                                <p:outputLabel for="fecha_inicio" value="#{msg.fecha_inicio}:" />
                                <p:calendar id="fecha_inicio" value="#{actividadSimpleBacking.actividadSimple.fecha_inicio}" required="true" 
                                            requiredMessage="#{msg.camporequerido}" />
                                <p:outputLabel for="fecha_fin" value="#{msg.fecha_fin}:" />
                                <p:calendar id="fecha_fin" value="#{actividadSimpleBacking.actividadSimple.fecha_fin}" required="true" 
                                            requiredMessage="#{msg.camporequerido}" />

                                <p:outputLabel for="resolucion" value="#{msg.resolucion}:" />
                                <p:inputText id="resolucion" value="#{actividadSimpleBacking.actividadSimple.resolucion}" 
                                             required="true" 
                                             requiredMessage="#{msg.camporequerido}"/> 
                                <p:outputLabel for="expediente" value="#{msg.expediente}:" />
                                <p:inputText id="expediente" value="#{actividadSimpleBacking.actividadSimple.expediente}" 
                                             required="true" 
                                             requiredMessage="#{msg.camporequerido}"/> 
                            </h:panelGrid>

                            <h:panelGrid columns="6" cellpadding="2" >
                                <p:outputLabel for="convocatoria" value="#{msg.convocatoria}:" />
                                <p:selectOneMenu id="convocatoria" value="#{actividadSimpleBacking.actividadSimple.convocatoria}" converter="convocatoriaConverter" filter="true"  required="true" 
                                                 requiredMessage="#{msg.camporequerido}" >
                                    <f:selectItem itemLabel="#{msg.elegir}" itemValue="#{null}" noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{actividadSimpleBacking.listaDeConvocatorias()}" var="convocatorias" itemLabel="#{convocatorias.nombre}" itemValue="#{convocatorias}" />
                                </p:selectOneMenu>

                                <p:outputLabel for="lineaEstrategia" value="#{msg.LineaEstrategia}:" />
                                <p:selectOneMenu id="lineaEstrategia" value="#{actividadSimpleBacking.actividadSimple.lineaEstrategia}" converter="lineaDeEstrategiaConverter" filter="true"  required="true" 
                                                 requiredMessage="#{msg.camporequerido}" >
                                    <f:selectItem itemLabel="#{msg.elegir}" itemValue="#{null}" noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{actividadSimpleBacking.listaDeEstrategias()}" var="estrategias" itemLabel="#{estrategias.nombre}" itemValue="#{estrategias}" />
                                </p:selectOneMenu>

                                <p:outputLabel for="ambito" value="#{msg.ambitoEjecucion}:" />
                                <p:selectOneMenu id="ambito" value="#{actividadSimpleBacking.actividadSimple.ambitoDeEjecucion}" converter="ambitoDeEjecucionConverter" filter="true"  required="true" 
                                                 requiredMessage="#{msg.camporequerido}" >
                                    <f:selectItem itemLabel="#{msg.elegir}" itemValue="#{null}" noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{actividadSimpleBacking.listaDeAmbitos()}" var="ambitos" itemLabel="#{ambitos.nombre}" itemValue="#{ambitos}" />
                                </p:selectOneMenu>
                                </h:panelGrid>
                                <p:separator />
                                <h:panelGrid columns="6" cellpadding="2" >
                                <p:outputLabel for="objetivo" value="#{msg.objetivo}:" />
                                <p:selectOneMenu id="objetivo" value="#{actividadSimpleBacking.impactoObjetivo.ods}" converter="odsConverter" filter="true"  >
                                                
                                    <f:selectItem itemLabel="#{msg.elegir}" itemValue="#{null}" noSelectionOption="true"></f:selectItem>
                                    <f:selectItems value="#{actividadSimpleBacking.listaDeObjetivos()}" var="objetivo" itemLabel="#{objetivo.nombre}" itemValue="#{objetivo}" />
                                </p:selectOneMenu>

                                <p:outputLabel for="peso" value="#{msg.peso}:" />
                                <p:inputText id="peso" value="#{actividadSimpleBacking.impactoObjetivo.peso}"  /> 

                                <p:commandButton value="#{msg.ingresar}" update="tabla objetivo peso deshacer" action="#{actividadSimpleBacking.insertarImpacto()}" icon="ui-icon-arrowreturnthick-1-e" >

                                </p:commandButton>
                                <p:commandButton id="deshacer" value="#{msg.deshacer}" disabled="#{actividadSimpleBacking.impactosVacio()}" update="deshacer tabla" action="#{actividadSimpleBacking.deshacer()}" icon="ui-icon-arrowreturnthick-1-w" />


                            </h:panelGrid>

                                <h:panelGrid id="tabla" columns="1" cellpadding="5"  >
                                    <p:dataTable scrollRows="20" scrollable="true" virtualScroll="true" scrollHeight="200" lazy="true" rows="8"  style="min-height: 200px; min-width: 750px;"  var="impacto" value="#{actividadSimpleBacking.actividadSimple.impactoObjetivo}" emptyMessage="#{msg.sinObjetivos}">
                                    <p:column headerText="#{msg.objetivo}">
                                        <h:outputText value="#{impacto.ods.nombre}" />
                                    </p:column>

                                    <p:column headerText="#{msg.peso}">
                                        <h:outputText value="#{impacto.peso}" />
                                    </p:column>
                                   
                                </p:dataTable>
                            </h:panelGrid>


                            <p:commandButton value="#{msg.borrar}" update="simple_new" action="#{actividadSimpleBacking.borrar()}" icon="ui-icon-cancel" />
                            <p:commandButton value="#{msg.crear}" update="simple_new" action="#{actividadSimpleBacking.create()}" icon="ui-icon-check" />
                



                        </p:panel>
                    </div>
                </div>
            </div>
        </h:form>
    </ui:define>    
</ui:composition>